// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'data/db/models/project_custom_fields.dart';
import 'data/db/models/projects.dart';
import 'data/db/models/task_field_custom_values.dart';
import 'data/db/models/tasks.dart';
import 'data/db/models/users.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4207759179491927503),
      name: 'ProjectCustomFields',
      lastPropertyId: const obx_int.IdUid(7, 3782952911920128469),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4715546740709583085),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7724461579340769014),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 586712444206224858),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5965436690232474263),
            name: 'projectId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 8687215269396465000),
            relationTarget: 'Projects'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3782952911920128469),
            name: 'fieldType',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1672770997612783188),
      name: 'TaskCustomFieldValues',
      lastPropertyId: const obx_int.IdUid(3, 4811163044080283535),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7557589717060449022),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5242670136544478353),
            name: 'taskId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 5987408169288675818),
            relationTarget: 'Tasks'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4811163044080283535),
            name: 'fieldId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 3984197417919690817),
            relationTarget: 'ProjectCustomFields')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 1292231007396300140),
      name: 'Projects',
      lastPropertyId: const obx_int.IdUid(4, 5046281179400629285),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3250718874433944303),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6291302941712960419),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5400944977400537794),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5046281179400629285),
            name: 'readMe',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 1470029959783021016),
            name: 'customFields',
            targetId: const obx_int.IdUid(1, 4207759179491927503))
      ],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(name: 'tasks', srcEntity: 'Tasks', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 7135919669571855799),
      name: 'Tasks',
      lastPropertyId: const obx_int.IdUid(4, 2646107159067864017),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 923063032073796067),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2435120272063104971),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4025503929025896332),
            name: 'body',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2646107159067864017),
            name: 'projectId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 6203653176727503638),
            relationTarget: 'Projects')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'customValues',
            srcEntity: 'TaskCustomFieldValues',
            srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 8050984854167619368),
      name: 'Users',
      lastPropertyId: const obx_int.IdUid(1, 2050342683567204832),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2050342683567204832),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 8050984854167619368),
      lastIndexId: const obx_int.IdUid(4, 6203653176727503638),
      lastRelationId: const obx_int.IdUid(1, 1470029959783021016),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [6449384158904302761, 4648203435906328928],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ProjectCustomFields: obx_int.EntityDefinition<ProjectCustomFields>(
        model: _entities[0],
        toOneRelations: (ProjectCustomFields object) => [object.project],
        toManyRelations: (ProjectCustomFields object) => {},
        getId: (ProjectCustomFields object) => object.id,
        setId: (ProjectCustomFields object, int id) {
          object.id = id;
        },
        objectToFB: (ProjectCustomFields object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final fieldTypeOffset = fbb.writeString(object.fieldType);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.project.targetId);
          fbb.addOffset(6, fieldTypeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final fieldTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = ProjectCustomFields(
              id: idParam,
              name: nameParam,
              description: descriptionParam,
              fieldType: fieldTypeParam);
          object.project.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.project.attach(store);
          return object;
        }),
    TaskCustomFieldValues: obx_int.EntityDefinition<TaskCustomFieldValues>(
        model: _entities[1],
        toOneRelations: (TaskCustomFieldValues object) =>
            [object.task, object.field],
        toManyRelations: (TaskCustomFieldValues object) => {},
        getId: (TaskCustomFieldValues object) => object.id,
        setId: (TaskCustomFieldValues object, int id) {
          object.id = id;
        },
        objectToFB: (TaskCustomFieldValues object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.task.targetId);
          fbb.addInt64(2, object.field.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = TaskCustomFieldValues(id: idParam);
          object.task.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.task.attach(store);
          object.field.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.field.attach(store);
          return object;
        }),
    Projects: obx_int.EntityDefinition<Projects>(
        model: _entities[2],
        toOneRelations: (Projects object) => [],
        toManyRelations: (Projects object) => {
              obx_int.RelInfo<Projects>.toMany(1, object.id):
                  object.customFields,
              obx_int.RelInfo<Tasks>.toOneBacklink(
                      4, object.id, (Tasks srcObject) => srcObject.project):
                  object.tasks
            },
        getId: (Projects object) => object.id,
        setId: (Projects object, int id) {
          object.id = id;
        },
        objectToFB: (Projects object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          final readMeOffset = fbb.writeString(object.readMe);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addOffset(3, readMeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final readMeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = Projects(
              id: idParam,
              title: titleParam,
              description: descriptionParam,
              readMe: readMeParam);
          obx_int.InternalToManyAccess.setRelInfo<Projects>(object.customFields,
              store, obx_int.RelInfo<Projects>.toMany(1, object.id));
          obx_int.InternalToManyAccess.setRelInfo<Projects>(
              object.tasks,
              store,
              obx_int.RelInfo<Tasks>.toOneBacklink(
                  4, object.id, (Tasks srcObject) => srcObject.project));
          return object;
        }),
    Tasks: obx_int.EntityDefinition<Tasks>(
        model: _entities[3],
        toOneRelations: (Tasks object) => [object.project],
        toManyRelations: (Tasks object) => {
              obx_int.RelInfo<TaskCustomFieldValues>.toOneBacklink(2, object.id,
                      (TaskCustomFieldValues srcObject) => srcObject.task):
                  object.customValues
            },
        getId: (Tasks object) => object.id,
        setId: (Tasks object, int id) {
          object.id = id;
        },
        objectToFB: (Tasks object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final bodyOffset =
              object.body == null ? null : fbb.writeString(object.body!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, bodyOffset);
          fbb.addInt64(3, object.project.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final bodyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final object = Tasks(id: idParam, title: titleParam, body: bodyParam);
          object.project.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.project.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Tasks>(
              object.customValues,
              store,
              obx_int.RelInfo<TaskCustomFieldValues>.toOneBacklink(2, object.id,
                  (TaskCustomFieldValues srcObject) => srcObject.task));
          return object;
        }),
    Users: obx_int.EntityDefinition<Users>(
        model: _entities[4],
        toOneRelations: (Users object) => [],
        toManyRelations: (Users object) => {},
        getId: (Users object) => object.id,
        setId: (Users object, int id) {
          object.id = id;
        },
        objectToFB: (Users object, fb.Builder fbb) {
          fbb.startTable(2);
          fbb.addInt64(0, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = Users(id: idParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProjectCustomFields] entity fields to define ObjectBox queries.
class ProjectCustomFields_ {
  /// See [ProjectCustomFields.id].
  static final id =
      obx.QueryIntegerProperty<ProjectCustomFields>(_entities[0].properties[0]);

  /// See [ProjectCustomFields.name].
  static final name =
      obx.QueryStringProperty<ProjectCustomFields>(_entities[0].properties[1]);

  /// See [ProjectCustomFields.description].
  static final description =
      obx.QueryStringProperty<ProjectCustomFields>(_entities[0].properties[2]);

  /// See [ProjectCustomFields.project].
  static final project = obx.QueryRelationToOne<ProjectCustomFields, Projects>(
      _entities[0].properties[3]);

  /// See [ProjectCustomFields.fieldType].
  static final fieldType =
      obx.QueryStringProperty<ProjectCustomFields>(_entities[0].properties[4]);
}

/// [TaskCustomFieldValues] entity fields to define ObjectBox queries.
class TaskCustomFieldValues_ {
  /// See [TaskCustomFieldValues.id].
  static final id = obx.QueryIntegerProperty<TaskCustomFieldValues>(
      _entities[1].properties[0]);

  /// See [TaskCustomFieldValues.task].
  static final task = obx.QueryRelationToOne<TaskCustomFieldValues, Tasks>(
      _entities[1].properties[1]);

  /// See [TaskCustomFieldValues.field].
  static final field =
      obx.QueryRelationToOne<TaskCustomFieldValues, ProjectCustomFields>(
          _entities[1].properties[2]);
}

/// [Projects] entity fields to define ObjectBox queries.
class Projects_ {
  /// See [Projects.id].
  static final id =
      obx.QueryIntegerProperty<Projects>(_entities[2].properties[0]);

  /// See [Projects.title].
  static final title =
      obx.QueryStringProperty<Projects>(_entities[2].properties[1]);

  /// See [Projects.description].
  static final description =
      obx.QueryStringProperty<Projects>(_entities[2].properties[2]);

  /// See [Projects.readMe].
  static final readMe =
      obx.QueryStringProperty<Projects>(_entities[2].properties[3]);

  /// see [Projects.customFields]
  static final customFields =
      obx.QueryRelationToMany<Projects, ProjectCustomFields>(
          _entities[2].relations[0]);

  /// see [Projects.tasks]
  static final tasks = obx.QueryBacklinkToMany<Tasks, Projects>(Tasks_.project);
}

/// [Tasks] entity fields to define ObjectBox queries.
class Tasks_ {
  /// See [Tasks.id].
  static final id = obx.QueryIntegerProperty<Tasks>(_entities[3].properties[0]);

  /// See [Tasks.title].
  static final title =
      obx.QueryStringProperty<Tasks>(_entities[3].properties[1]);

  /// See [Tasks.body].
  static final body =
      obx.QueryStringProperty<Tasks>(_entities[3].properties[2]);

  /// See [Tasks.project].
  static final project =
      obx.QueryRelationToOne<Tasks, Projects>(_entities[3].properties[3]);

  /// see [Tasks.customValues]
  static final customValues =
      obx.QueryBacklinkToMany<TaskCustomFieldValues, Tasks>(
          TaskCustomFieldValues_.task);
}

/// [Users] entity fields to define ObjectBox queries.
class Users_ {
  /// See [Users.id].
  static final id = obx.QueryIntegerProperty<Users>(_entities[4].properties[0]);
}
